spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Tushar@061289
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: a-string-secret-at-least-256-bits-long
  expiration: 1800000   # 30 minutes


server:
  port: 8081

logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
