spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

server:
  port: 8085

stripe:
  secret:
    key: <secret>

jwt:
  secret: a-string-secret-at-least-256-bits-long
  expiration: 1800000   # 30 minutes

management:
  endpoints:
    web:
      exposure:
        include: health,info
