spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

server:
  port: 8085

stripe:
  secret:
    key: sk_test_51RmxgzCcdhZAFvUEOIe1RyhGHQwcNTMW6ZPvVvOvSZmaUD6YpKinvvJcC7JtEsxlGrN4C1K24KtWSvyGtG2WspJE00dQNjJJce

management:
  endpoints:
    web:
      exposure:
        include: health,info

datasource:
  url: jdbc:mysql://localhost:3306/ecommerce
  username: root
  password: Tushar@061289
  driver-class-name: com.mysql.cj.jdbc.Driver