spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Tushar@061289
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  secret: a-string-secret-at-least-256-bits-long