spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: Tushar@061289
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: a-string-secret-at-least-256-bits-long